# Use Python
FROM python:3.10-slim

# Set working dir
WORKDIR /app

# Copy files
COPY requirements.txt .
COPY server.py .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 5000

# Run the app
CMD ["python", "server.py"]
